export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_BUFFER = 'SET_BUFFER';
export const TOGGLE_PLAYING_STATE = 'TOGGLE_PLAYING_STATE';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';