export const ADD_ITEM_TO_QUEUE = "ADD_ITEM_TO_QUEUE";
export const REMOVE_ITEM_FROM_QUEUE = "REMOVE_ITEM_FROM_QUEUE";
export const CREATE_QUEUE = "CREATE_QUEUE";
export const FETCH_QUEUE = "FETCH_QUEUE";