export const SHIFT_SELECTED_SEARCHED_ITEM = 'SHIFT_SELECTED_SEARCHED_ITEM';
export const SET_CURRENT_PLAYING_ITEM_BY_ID = 'SET_CURRENT_PLAYING_ITEM_BY_ID';
export const PAUSE_PLAYED_ITEM_IN_SEARCH = 'PAUSE_PLAYED_ITEM_IN_SEARCH';
export const ADD_ITEM_TO_QUEUE_BY_SEARCH_INDEX = 'ADD_ITEM_TO_QUEUE_BY_SEARCH_INDEX';
export const ADD_ITEM_AND_CLOSE_SEARCH = 'ADD_ITEM_AND_CLOSE_SEARCH';
export const SEARCH_FIRED = 'SEARCH_FIRED'