export const OPEN_VIDEO_SEARCH = 'OPEN_VIDEO_SEARCH';
export const CLOSE_VIDEO_SEARCH = 'CLOSE_VIDEO_SEARCH';
export const CLEAR_SEARCH_VALUE = 'CLEAR_SEARCH_VALUE';
export const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED';
export const CHANGE_SEARCH_RESULTS = 'CHANGE_SEARCH_RESULTS';
export const CHANGE_SELECTED_SEARCHED_ITEM = 'CHANGE_SELECTED_SEARCHED_ITEM';
export const CHANGE_PLAYED_ITEM_FROM_SEARCH = 'CHANGE_PLAYED_ITEM_FROM_SEARCH';